# Generated by Django 4.0.2 on 2022-03-07 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('litreview', '0005_alter_userfollows_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='answer_review',
            field=models.BooleanField(default=False),
        ),
    ]
