# Generated by Django 4.0.2 on 2022-03-13 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('litreview', '0008_remove_ticket_answer_review_review_answer_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='answer_review',
            field=models.BooleanField(default=False),
        ),
    ]
